-- https://school.programmers.co.kr/learn/courses/30/lessons/131533

SELECT
  p.PRODUCT_CODE AS PRODUCT_CODE,
  (p.PRICE * SUM(os.SALES_AMOUNT)) AS SALES
FROM PRODUCT AS p
INNER JOIN OFFLINE_SALE AS os ON p.PRODUCT_ID = os.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SALES DESC, p.PRODUCT_CODE ASC