SELECT
  MONTH(crh.START_DATE) AS 'MONTH',
  crh.CAR_ID AS 'CAR_ID',
  COUNT(*) AS 'RECORDS'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS crh
INNER JOIN
(
  SELECT CAR_ID
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
  WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
  GROUP BY CAR_ID
  HAVING COUNT(*) >= 5
) AS in_crh ON crh.CAR_ID = in_crh.CAR_ID
WHERE DATE_FORMAT(crh.START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
GROUP BY MONTH, crh.CAR_ID
ORDER BY MONTH, crh.CAR_ID DESC