SELECT 
  crcc.CAR_TYPE,
  COUNT(crcc.CAR_TYPE) AS CARS
FROM CAR_RENTAL_COMPANY_CAR AS crcc
WHERE OPTIONS LIKE '%열선시트%' OR OPTIONS LIKE '%통풍시트%' OR OPTIONS LIKE '%가죽시트%'
GROUP BY crcc.CAR_TYPE
ORDER BY crcc.CAR_TYPE ASC;