SELECT
 ugu.USER_ID,
 ugu.NICKNAME AS NICKNAME,
 CONCAT_WS(' ', ugu.CITY, ugu.STREET_ADDRESS1, ugu.STREET_ADDRESS2) AS '전체주소',
 CONCAT(
  SUBSTRING(ugu.TLNO, 1, 3), '-',
  SUBSTRING(ugu.TLNO, 4, 4), '-',
  SUBSTRING(ugu.TLNO, 8, 4)
 ) AS '전화번호'
FROM USED_GOODS_USER AS ugu
INNER JOIN USED_GOODS_BOARD AS ugb ON ugu.USER_ID = ugb.WRITER_ID
GROUP BY ugb.WRITER_ID
HAVING 3 <= COUNT(ugb.WRITER_ID)
ORDER BY ugu.USER_ID DESC