-- https://school.programmers.co.kr/learn/courses/30/lessons/298519

-- WITH를 이용한 풀이 방법

WITH SUB_TYPE_AVG_LENGTH AS
(
  SELECT
    AVG(IFNULL(fi.LENGTH, 10)) AS AVG_LENGTH,
    fi.FISH_TYPE
  FROM FISH_INFO AS fi
  GROUP BY fi.FISH_TYPE
)

SELECT
  COUNT(fi.ID) AS FISH_COUNT,
  MAX(fi.LENGTH) AS MAX_LENGTH,
  fi.FISH_TYPE
FROM FISH_INFO AS fi
INNER JOIN SUB_TYPE_AVG_LENGTH AS stal
  ON fi.FISH_TYPE = stal.FISH_TYPE
    AND stal.AVG_LENGTH >= 33
GROUP BY fi.FISH_TYPE
ORDER BY fi.FISH_TYPE ASC

-- HAVING을 이용한 풀이 방법

SELECT
  COUNT(fi.ID) AS FISH_COUNT,
  MAX(fi.LENGTH) AS MAX_LENGTH,
  fi.FISH_TYPE
FROM FISH_INFO AS fi
GROUP BY fi.FISH_TYPE
HAVING AVG(IFNULL(LENGTH, 10)) >= 33
ORDER BY fi.FISH_TYPE ASC
