SELECT
  ugu.USER_ID AS USER_ID,
  ugu.NICKNAME AS NICKNAME,
  SUM (ugb.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER AS ugu
INNER JOIN USED_GOODS_BOARD AS ugb ON ugu.USER_ID = ugb.WRITER_ID
WHERE ugb.STATUS = 'DONE'
GROUP BY ugb.WRITER_ID
HAVING 700000 <= TOTAL_SALES
ORDER BY TOTAL_SALES ASC