SELECT
  ccrh.HISTORY_ID,
  ccrh.CAR_ID,
  DATE_FORMAT(ccrh.START_DATE, '%Y-%m-%d') AS START_DATE,
  DATE_FORMAT(ccrh.END_DATE, '%Y-%m-%d') AS END_DATE,
  CASE
    WHEN 30 <= (DATEDIFF(ccrh.END_DATE, ccrh.START_DATE) + 1) 
    THEN '장기 대여'
    ELSE '단기 대여'
  END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS ccrh
WHERE ccrh.START_DATE BETWEEN '2022-09-01' AND '2022-09-30' 
ORDER BY ccrh.HISTORY_ID DESC
