SELECT
  b.BOOK_ID,
  DATE_FORMAT
  (
    b.PUBLISHED_DATE, '%Y-%m-%d'
  ) AS PUBLISHED_DATE
FROM BOOK AS b
WHERE b.CATEGORY = '인문'
  AND DATE_FORMAT(b.PUBLISHED_DATE, '%Y') = '2021'
ORDER BY b.PUBLISHED_DATE ASC
