-- https://school.programmers.co.kr/learn/courses/30/lessons/301649

WITH COLONY_SIZE_PERCENT_RANK AS (
  SELECT
    ed.ID,
    PERCENT_RANK() OVER(ORDER BY ed.SIZE_OF_COLONY DESC) 'SIZE_PERCENT_RANK'
  FROM ECOLI_DATA AS ed
)

SELECT
  cspr.ID,
  CASE
    WHEN cspr.SIZE_PERCENT_RANK <= 0.25 THEN 'CRITICAL'
    WHEN cspr.SIZE_PERCENT_RANK <= 0.50 THEN 'HIGH'
    WHEN cspr.SIZE_PERCENT_RANK <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW'
  END 'COLONY_NAME'
FROM COLONY_SIZE_PERCENT_RANK AS cspr
ORDER BY cspr.ID ASC
