SELECT
  DATE_FORMAT(os.SALES_DATE, '%Y') AS 'YEAR',
  DATE_FORMAT(os.SALES_DATE, '%m') AS 'MONTH',
  COUNT(DISTINCT(os.USER_ID)) 'PUCHASED_USERS',
  ROUND
  (
    COUNT(DISTINCT(os.USER_ID)) /
    (
        SELECT COUNT(DISTINCT sub_ui.USER_ID)
        FROM USER_INFO AS sub_ui
        WHERE DATE_FORMAT(sub_ui.JOINED, '%Y') = 2021
    ),
    1
  ) AS 'PUCHASED_RATIO'
FROM ONLINE_SALE AS os
INNER JOIN USER_INFO AS ui ON os.USER_ID = ui.USER_ID
WHERE DATE_FORMAT(ui.JOINED, '%Y') = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH
