-- https://school.programmers.co.kr/learn/courses/30/lessons/299308

SELECT
 CASE 
    WHEN QUARTER(ed.DIFFERENTIATION_DATE) = 1 THEN '1Q'
    WHEN QUARTER(ed.DIFFERENTIATION_DATE) = 2 THEN '2Q'
    WHEN QUARTER(ed.DIFFERENTIATION_DATE) = 3 THEN '3Q'
    WHEN QUARTER(ed.DIFFERENTIATION_DATE) = 4 THEN '4Q'
  END AS QUARTER,
  COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA AS ed
GROUP BY QUARTER
ORDER BY QUARTER ASC;
